export const VALUE_TYPE = {
  LABEL: 33,
  TIMESTAMP: 32,
  IDENTIFIER: 31,
  PERCENTAGE: 30,
  NUMBER: 29,
  VALUE_ARRAY: 27,
  COLOR: 26,
  TRIPLE: 25,
  PIXELS: 19,
  VALUE_ADDRESS: 18,
  BOOL: 2,
  NULL: 1,
  UNDEFINED: 0,
} as const;

export const BROADCAST_ID = 255;
