export const VALUE_TYPE = {
  TIMESTAMP: 32,
  LABEL: 31,
  PERCENTAGE: 30,
  NUMBER: 29,
  VALUE_ARRAY: 27,
  COLOR: 26,
  TRIPLE: 25,
  PIXELS: 19,
  VALUE_ADDRESS: 18,
  BOOL: 2,
  NULL: 1,
  UNDEFINED: 0,
} as const;

export const BROADCAST_ID = 0xff;

export const COMMAND_FLAGS = {
  UNSUPPORTED_COMMND_RESPONSE: 255, // TODO change FLAG_OTA_BEGIN to not be 255.

  // legacy FW update flags
  OTA_BEGIN: 255, // legacy
  OTA_WRITE: 0, // legacy // TODO change FLAG_OTA_WRITE to not be 0.
  OTA_END: 254, // legacy
  OTA_RESET: 253, // legacy

  DEVICE_REBOOT_REQUEST: 5, // legacy
  DEVICE_DISCONNECT_REQUEST: 6,

  CONFIG_UPDATE_REQUEST: 10,
  CONFIG_UPDATE_RESPONSE: 11,

  // --- Former CommandFlag begin ---
  PEER_CONNECTED: 101,
  PEER_DISCONNECTED: 102,

  REINTERPRET_TNGL: 104,
  SET_TIMELINE: 105,

  EMIT_EVENT: 111,
  EMIT_TIMESTAMP_EVENT: 112,
  EMIT_COLOR_EVENT: 113,
  EMIT_PERCENTAGE_EVENT: 114,
  EMIT_LABEL_EVENT: 115,
  // --- Former CommandFlag end ---

  READ_PORT_PIXELS_REQUEST: 190,
  READ_PORT_PIXELS_RESPONSE: 191,
  WRITE_PORT_PIXELS_REQUEST: 192,
  WRITE_PORT_PIXELS_RESPONSE: 193,
  EVALUATE_ON_CONTROLLER_REQUEST: 194,
  EVALUATE_ON_CONTROLLER_RESPONSE: 195,

  READ_CONTROLLER_CODES_REQUEST: 196,
  READ_CONTROLLER_CODES_RESPONSE: 197,
  WRITE_CONTROLLER_CODES_REQUEST: 198,
  WRITE_CONTROLLER_CODES_RESPONSE: 199,
  READ_OWNER_SIGNATURE_REQUEST: 200,
  READ_OWNER_SIGNATURE_RESPONSE: 201,

  WRITE_CONTROLLER_NAME_REQUEST: 202,
  WRITE_CONTROLLER_NAME_RESPONSE: 203,
  READ_CONTROLLER_NAME_REQUEST: 204,
  READ_CONTROLLER_NAME_RESPONSE: 205,

  MERGE_EVENT_HISTORY_REQUEST: 206,
  MERGE_EVENT_HISTORY_RESPONSE: 207,
  ERASE_EVENT_HISTORY_REQUEST: 208,
  ERASE_EVENT_HISTORY_RESPONSE: 209,

  REQUEST_PEER_REQUEST: 210,
  REQUEST_PEER_RESPONSE: 211,

  EVENT_HISTORY_BC_REQUEST: 212,
  EVENT_HISTORY_BC_RESPONSE: 213,

  VISIBLE_PEERS_REQUEST: 214,
  VISIBLE_PEERS_RESPONSE: 215,

  FW_UPDATE_PEER_REQUEST: 216,
  FW_UPDATE_PEER_RESPONSE: 217,

  SYNC_STATE_REQUEST: 218,
  SYNC_STATE_RESPONSE: 219,

  SAVE_STATE_REQUEST: 220,
  SAVE_STATE_RESPONSE: 221,

  SLEEP_REQUEST: 222,
  SLEEP_RESPONSE: 223,
  CONNECTED_PEERS_INFO_REQUEST: 224,
  CONNECTED_PEERS_INFO_RESPONSE: 225,

  DEVICE_CONFIG_REQUEST: 226,
  DEVICE_CONFIG_RESPONSE: 227,
  ROM_PHY_VDD33_REQUEST: 228,
  ROM_PHY_VDD33_RESPONSE: 229,
  VOLTAGE_ON_PIN_REQUEST: 230,
  VOLTAGE_ON_PIN_RESPONSE: 231,

  CHANGE_DATARATE_REQUEST: 232,
  CHANGE_DATARATE_RESPONSE: 233,

  FW_VERSION_REQUEST: 234,
  FW_VERSION_RESPONSE: 235,
  ERASE_OWNER_REQUEST: 236,
  ERASE_OWNER_RESPONSE: 237,

  TNGL_FINGERPRINT_REQUEST: 242,
  TNGL_FINGERPRINT_RESPONSE: 243,
  TIMELINE_REQUEST: 244,
  TIMELINE_RESPONSE: 245,

  CONNECT_REQUEST: 238,
  CONNECT_RESPONSE: 239,
  ADOPT_REQUEST: 240,
  ADOPT_RESPONSE: 241,
};
