name: Slack Notifier

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./scripts

      - name: Run Slack notifier
        run: node slack-commit-share.js
        working-directory: ./scripts

      - name: Run ClickUp notifier
        run: node clickup-commit-share.js
        working-directory: ./scripts
